name: Basic C/C++ Security Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck
          pip install semgrep

      - name: Run Cppcheck
        run: |
          cppcheck --enable=warning,performance,portability \
                   --template="{file}:{line}: {severity}: {message}" \
                   --output-file=cppcheck-results.txt .

      - name: Run Semgrep
        run: |
          semgrep scan --config=auto \
                      --output=semgrep-results.json \
                      --json .

      - name: Compare Results
        run: |
          echo "# Security Analysis Comparison" > comparison.md
          
          echo "## Cppcheck Findings" >> comparison.md
          if [ -s cppcheck-results.txt ]; then
            cat cppcheck-results.txt >> comparison.md
          else
            echo "No issues found" >> comparison.md
          fi
          
          echo -e "\n## Semgrep Findings" >> comparison.md
          if [ -s semgrep-results.json ]; then
            jq -r '.results[]? | "- \(.extra.message) in \(.path):\(.start.line)"' semgrep-results.json >> comparison.md
          else
            echo "No issues found" >> comparison.md
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: security-findings
          path: comparison.md